<?php
/**
#    Copyright (C) 2013 Global Era (http://www.globalera.com). All Rights Reserved
#    @author Serenus Infotech magento@serenusinfotech.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see http://www.gnu.org/licenses/.
**/

$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>


<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
    <p class="product-image product-image-zoom">
        <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
    <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
    <div class="zoom">
        <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
        <div id="track">
            <div id="handle"></div>
        </div>
        <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
    </div>
    <script type="text/javascript">
        //<![CDATA[
        Event.observe(window, 'load', function() {
            product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
        });
        //]]>
    </script>
<?php else: ?>
    <p class="product-image product-image-zoom">
        <?php
        $_img = '<img  id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
    <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
    <div class="zoom">
        <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
        <div id="track">
            <div id="handle"></div>
        </div>
        <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
    </div>
    <script type="text/javascript">
        //<![CDATA[
        Event.observe(window, 'load', function() {
            product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
        });
        //]]>
    </script>
<?php endif; ?>
<?php
if($_product->getExternalImage()){
    ?>
    <div class="more-views11">
        <h2><?php echo $this->__('More Views') ?></h2>
        <ul>
            <li>
                <a href="#" onclick="popWin('<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" width="56px;"/>
                </a>
            </li>
        </ul>
    </div>
    <?php
}else{
    if (count($this->getGalleryImages()) > 0): ?>
        <div class="more-views">
            <h2><?php echo $this->__('More Views') ?></h2>
            <ul>
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <li>
                    <a href="#" onclick="popWin('<?php echo $_image->getUrl() ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                        <img src="<?php echo $_image->getUrl(); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php
        endif;
}
?>


